### ISSUE TITLE
Unable to run demo.py

### ISSUE THREAD

**Issue by linux-devil** [mystic123/tensorflow-yolo-v3#11]
Hi when I run demo.py it fails with following error : 

UnimplementedError (see above for traceback): Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: detector/darknet-53/Conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](detector/truediv, detector/darknet-53/Conv/weights/read)]]

`2018-07-05 12:20:04.395172: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: detector/darknet-53/Conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](detector/truediv, detector/darknet-53/Conv/weights/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./demo.py", line 76, in <module>
    tf.app.run()
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./demo.py", line 65, in main
    detected_boxes = sess.run(boxes, feed_dict={inputs: [np.array(img_resized, dtype=np.float32)]})
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: detector/darknet-53/Conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](detector/truediv, detector/darknet-53/Conv/weights/read)]]

Caused by op 'detector/darknet-53/Conv/Conv2D', defined at:
  File "./demo.py", line 76, in <module>
    tf.app.run()
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./demo.py", line 57, in main
    detections = yolo_v3(inputs, len(classes), data_format='NCHW')
  File "/home/harshit/Documents/tensorflow-yolo-v3/yolo_v3.py", line 228, in yolo_v3
    route_1, route_2, inputs = darknet53(inputs)
  File "/home/harshit/Documents/tensorflow-yolo-v3/yolo_v3.py", line 19, in darknet53
    inputs = _conv2d_fixed_padding(inputs, 32, 3)
  File "/home/harshit/Documents/tensorflow-yolo-v3/yolo_v3.py", line 50, in _conv2d_fixed_padding
    inputs = slim.conv2d(inputs, filters, kernel_size, stride=strides, padding=('SAME' if strides == 1 else 'VALID'))
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1049, in convolution
    outputs = layer.apply(inputs)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 828, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/layers/convolutional.py", line 168, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 956, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/harshit/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: detector/darknet-53/Conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](detector/truediv, detector/darknet-53/Conv/weights/read)]]
`

**Comment by mystic123** [comment]
At first glimpse, it looks like you are trying to run the detector on CPU in NCHW order. You should either run it on GPU or change data format to NHWC.

**Comment by linux-devil** [comment]
@mystic123 I managed to install tensorflow-gpu and run above but again similar error came was thrown. Further I changed the NCHW format and this is resolved. I wanted to save sess and meta file is not saved and it fails. I fail to get  metafile for the graph. I am using following to save sess:
`    saver = tf.train.Saver()
    with tf.Session() as sess:
        sess.run(load_ops)
        saver.save(sess,'/home/')
`

**Comment by mystic123** [comment]
>  I managed to install tensorflow-gpu and run above but again similar error came was thrown. Further I changed the NCHW format and this is resolved.

Maybe it was still using CPU version, even after installing tensorflow-gpu. I had similar problem - had to uninstall tensorflow and tensorflow-gpu and then install tensorflow-gpu.

>  wanted to save sess and meta file is not saved and it fails. I fail to get metafile for the graph.

@linux-devil  which version of tensorflow are you using?

**Comment by linux-devil** [comment]
tensorflow 1.8.0

**Comment by shrybht** [comment]
Hi,

I'm facing the same error as you mentioned:
`UnimplementedError (see above for traceback): Generic conv implementation only s upports NHWC tensor format for now.                                                       [[Node: detector/darknet-53/Conv/Conv2D = Conv2D[T=DT_FLOAT, data_forma t="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudn n_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](detector/ transpose, ArithmeticOptimizer/detector/darknet-53/Conv/weights_scaled_detector/ darknet-53/Conv/Conv2D)]]`

Could you please tell me how to solve the error and run the detector on CPU?
