### ISSUE TITLE
cannot reshape array of size 4607 into shape (18,256,1,1)

### ISSUE THREAD

**Issue by firstxx** [mystic123/tensorflow-yolo-v3#62]
I convert yolov3.weights to a pb file. It is OK. When I tried to convert a pre-training model, the following errors occurred. The structure of pre-training model is the same as that of yolov3.weight. The only difference is that it has only one class.

Traceback (most recent call last):
  File "convert_weights_pb.py", line 53, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\fr\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "convert_weights_pb.py", line 43, in main
    load_ops = load_weights(tf.global_variables(scope='detector'), FLAGS.weights_file)
  File "D:\codes\converter\tensorflow-yolo-v3\utils.py", line 120, in load_weights
    (shape[3], shape[2], shape[0], shape[1]))
ValueError: cannot reshape array of size 4607 into shape (18,256,1,1)

**Comment by NightFury10497** [comment]
./convert_weights_pb.py --class_name coco.names --data_format NHWC --weight_file yolov3.weights
Traceback (most recent call last):
  File "./convert_weights_pb.py", line 52, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./convert_weights_pb.py", line 42, in main
    load_ops = load_weights(tf.global_variables(scope='detector'), FLAGS.weights_file)
  File "/home/night/Desktop/github/tensorflow-yolo-v3/utils.py", line 115, in load_weights
    (shape[3], shape[2], shape[0], shape[1]))
ValueError: cannot reshape array of size 4607 into shape (18,256,1,1)

**Comment by Yogita98** [comment]
**Well I got this issue as well**
Traceback (most recent call last):
  File "convert_weights_pb.py", line 52, in <module>
    tf.app.run()
  File "C:\Users\bhati\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "convert_weights_pb.py", line 42, in main
    load_ops = load_weights(tf.global_variables(scope='detector'), FLAGS.weights_file)
  File "C:\yogita-2\tensorflow-yolo-v3\utils.py", line 115, in load_weights
    (shape[3], shape[2], shape[0], shape[1]))
ValueError: cannot reshape array of size 264248 into shape (256,128,3,3)

**Comment by xiayq1** [comment]
Is there anybody who have solved the problem?

**Comment by karandeepdps** [comment]
Change your labels.txt to appropriate length.

**Comment by ohUMR** [comment]
> Change your labels.txt to appropriate length.

what's that mean? the process when run convert_weights_pb.py does not require any txt file

**Comment by karandeepdps** [comment]
--class_names 

> > Change your labels.txt to appropriate length.
> 
> what's that mean? the process when run convert_weights_pb.py does not require any txt file

**Comment by ohUMR** [comment]
I got the same reason, and here's how I solve it.

First,check is your environment right.

I trained my weights file on Win 10 at first, after debug, I find the weight size is not equal to the network actually needed, in my case, the size of my one-class weights is 8676243 while the network needs 8676244.

After changing into Ubuntu, I use Ubuntu 18.04(Ubuntu 16.04 should be the same), and retrained my one-class yolov3-tinny model, I use this weights to convert into pb format, it finally works

So check your environment, I advice you train your model on Ubuntu and use tensorflow-gpu V1.12.

Finally, I'd like anyone to tell me why it's different in Windows and Ubuntu, in my guess, it's probably the reason of the value's precision is different in Ubuntu and Windows.

**Comment by phiSgr** [comment]
So some of us has the weights off by 32 bits. 
Is this related? https://github.com/pjreddie/darknet/issues/497 The `seen` may be 32bit or 64bit long.

Could you guys try reading 32 bits fewer by changing count to 4 in ` _ = np.fromfile(fp, dtype=np.int32, count=5)`?

**Comment by wangluolaowu** [comment]
I find the error is because the class_names  file, the last line is  blank line, delete the blank line , the problom solving

**Comment by violet17** [comment]
> Could you try reading 32 bits fewer by changing `count` to `4` in ` _ = np.fromfile(fp, dtype=np.int32, count=5)` in utils?
 It didn't work for me..

**Comment by phiSgr** [comment]
Changing the `count` to 4 may fix the issue only if the number is off by one.
E.g. 4067 = 18 * 256 - 1 in the title.

**Comment by aditya-vora** [comment]
I am not sure why the comment of @wangluolaowu has been down voted. It's actually the solution that worked for me.

**Comment by stangier** [comment]
Has anyone that had a correct .names file solved this problem yet? @firstxx @NightFury10497 @Yogita98 
I am having the same problem.

**Comment by OctaM** [comment]
I have the correct .names and still have the problem. Any idea?

**Comment by ceciliaAI** [comment]
ValueError: cannot reshape array of size 3072 into shape (18,256,1,1)
anyone can help me?

**Comment by abuzahid** [comment]
This happens for problem in (.names) file. You should check tow things to solve this.
1. If you are training on all classes please check if there is extra new line at the last of class names.
2. If you are training on specific some classes please remove the extra class from (.names) file either you used all class names during training.

**Comment by aleksandreK** [comment]
I had the same issue, turned out I was giving .data file as --names_path - instead of .names file.
Giving correct arguments fixed it for me, so make sure that you're giving the right ones.

**Comment by ionutvacariu** [comment]
> This happens for problem in (.names) file. You should check tow things to solve this.
> 
> 1. If you are training on all classes please check if there is extra new line at the last of class names.
> 2. If you are training on specific some classes please remove the extra class from (.names) file either you used all class names during training.

I've tried both. no extra line, all classes present ( 36 ) and still have exception :(

**Comment by 7wdeepin** [comment]
Convert 
```python
_ = np.fromfile(fp, dtype=np.int32, count=5)
```
to
```python
_ = np.fromfile(fp, dtype=np.int32, count=4)
```
in `utils.py` (line 70). It works to me.

**Comment by marcosmedice** [comment]
I solved the problem editting the /data/classes/: coco.names and yymnist.names archives, using the number of classes and those names that I trained using my custom dataset

**Comment by LucasMahieu** [comment]
related to : https://github.com/mystic123/tensorflow-yolo-v3/pull/105
